routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SaleController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [SaleController::class, 'index'])->name('home');

Auth::routes();


Route::middleware('auth')->group(function () {
    
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    Route::resource('clients',ClientController::class);
    Route::resource('products',ProductController::class);
    Route::resource('sales',SaleController::class);
});

app/Models/Sale.php
<?php

namespace App\Models;

use App\Models\Client;
use App\Models\SaleDetail;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sale extends Model
{
    use SoftDeletes;


    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'sales';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'client_id',
        'total_amount',
        'discount',
        'iva',
        'date_sale'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];

    /**
     * The attributes that should be cast to datetime types.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];


    /**
     * Returns the client object related to the  sale
     * 
     * @return Array
     */
    public function client () 
    {
        return $this->belongsTo(Client::class)->withTrashed();
    }

    /**
     * Returns the sales related to the client
     * 
     * @return Array
     */
    public function details () 
    {
        return $this->HasMany(SaleDetail::class);
    }
}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\Sale;
use App\Models\Client;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use App\Services\SaleService; 
use App\Http\Requests\StoreSaleRequest;

/**
 * Class SaleController
 * @package App\Http\Controllers
 */
class SaleController extends Controller
{
    /**
     * @var $testService
     */
    protected $saleService;


    public function __construct(
        SaleService $saleService
    )
    {
        $this->saleService = $saleService;
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $sales = Sale::paginate();

        return view('sale.index', compact('sales'))
            ->with('i', (request()->input('page', 1) - 1) * $sales->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $sale = new Sale();
        $clients = Client::where('status',1)->pluck('name', 'id');
        $products = Product::where('quantity', '>', 0)->get();
        return view('sale.create', compact('sale','clients','products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreSaleRequest $request
     * @return Response
     */
    public function store(StoreSaleRequest $request)
    {
        try {

            $sale = Sale::create($request->all());

            $saleDetail = $this->saleService->createSaleDetail($request->details,$sale->id);
            
            if ($saleDetail['success']) 

                return redirect()->route('sales.index')
                ->with('success', 'Sale created successfully.');
            
        } catch (Exception $exception) {

            return redirect()->route('sales.index')
            ->with('error', $exception);
        }
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $sale = Sale::find($id);

        if (!$sale) {
            return redirect()->route('sales.index')
            ->with('error', 'Sale not fount.');
        }

        return view('sale.show', compact('sale'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sale = Sale::find($id);
        $clients = Client::where('status',1)->pluck('name', 'id');
        $products = Product::where('quantity','>',0)->get();

        return view('sale.edit', compact('sale','clients','products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Sale $sale
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sale $sale)
    {
        $sale->update($request->all());

        $saleDetail = $this->saleService->createSaleDetail($request->details,$sale->id);
        
        return redirect()->route('sales.index')
            ->with('success', 'Sale updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $sale = Sale::find($id)->delete();

        return redirect()->route('sales.index')
            ->with('success', 'Sale deleted successfully');
    }
}

resources/views/sale/add_product.blade.php
<div class="modal" tabindex="-1" role="dialog" id="add_product">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add product </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
             <label  for="client">Product</label>
                <select class="custom-select" id="product">
                    <option selected>Choose...</option>
                    @foreach ($products as $product)
                        <option quantity="{{ $product->quantity }}" price="{{ $product->price }}" value="{{ $product->id }}" name="{{ $product->name }}">{{ $product->name }}</option>                       
                    @endforeach
                </select>
            
        </div>
        <div class="form-group">
            <input type="number" class="form-control" id="quantity" placeholder="Quantity">
        </div>

        <div id="error" class="error"> </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="add_product_button"  class="btn btn-primary">Add</button>
        <button type="button" style="display:none;" id="edit_product_button"  class="btn btn-primary">Edit</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

resources/views/sale/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Sale
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                @includeif('partials.errors')
                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Sale</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" id="form_sales" action="{{ route('sales.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('sale.form')
                            <div class="box-footer mt20">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="btn btn-primary" href="{{ route('sales.index') }}"> Back</a>
                            </div>

                        </form>
                    </div>

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/sale/details.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        <div class="card-header">
            <span class="card-title">Sale Details</span> <a style="margin-left:10px;" class="btn btn-sm btn-primary " data-toggle="modal" data-target="#add_product" href=""><i class="fa fa-fw fa-eye"></i> Add New</a>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="table_details">
                    <thead class="thead">
                        <tr>
                            <th>#</th>
                            <th>Product</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Subtotal</th>
                            <th>Iva</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="details_table">
                                    @foreach ($sale->details as $detail)
                                        <tr>
                                            <td id="{{ $detail->product->id }}">{{ 1 }}</td>
                                            
											<td> {{ $detail->product->name }}</td>
											<td> {{ $detail->product->price }}</td>
											<td> {{ $detail->quantity  }}</td>
                                            <td> {{ $detail->subtotal }}</td>
                                            <td> {{$detail->subtotal * 0.19}}</td>
                                            <td>
                                                <a class='btn btn-sm btn-success edit_button' id='edit_detail_{{$detail->product->id}}'>Edit</a>
                                                <a type='submit' id='delete_detail_{{$detail->product->id}}' class='btn btn-danger btn-sm delete_button'><i class='fa fa-fw fa-trash'></i> Delete</a>
                                            </td>
                                        </tr>
                                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@include('sale.add_product')

resources/views/sale/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Sale
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Sale</span>
                    </div>
                    <div class="card-body">
                        <form method="POST"  id="form_sales" action="{{ route('sales.update', $sale->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('sale.form')
                            <div class="box-footer mt20">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="btn btn-primary" href="{{ route('sales.index') }}"> Back</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/sale/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            
            {{ Form::label('client_id', 'Client :')}}
            {!! Form::select('client_id', $clients, null, ['class' => 'form-control']) !!}
            
        </div>
        <div class="form-group">
            {{ Form::label('Date') }}
            {{ Form::date('date_sale', $sale->date_sale ? date('Y-m-d', strtotime($sale->date_sale)) : date('Y-m-d')  , ['class' => 'form-control' . ($errors->has('date_sale') ? ' is-invalid' : '')]) }}
            {!! $errors->first('date_sale', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('iva') }}
            {{ Form::text('iva', $sale->iva, ['class' => 'form-control' . ($errors->has('iva') ? ' is-invalid' : ''), 'placeholder' => 'Iva' ,'readonly' =>true]) }}
            {!! $errors->first('iva', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('total_amount') }}
            {{ Form::text('total_amount', $sale->total_amount, ['class' => 'form-control' . ($errors->has('total_amount') ? ' is-invalid' : ''), 'placeholder' => 'Total Amount' ,'readonly' =>true]) }}
            {!! $errors->first('total_amount', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('discount') }}
            {{ Form::text('discount', $sale->discount, ['class' => 'form-control' . ($errors->has('discount') ? ' is-invalid' : ''), 'placeholder' => 'Discount','readonly' =>true]) }}
            {!! $errors->first('discount', '<div class="invalid-feedback">:message</p>') !!}
        </div>


    </div>
    @include('sale.details')
   
</div>

resources/views/sale/index.blade.php
@extends('layouts.app')

@section('template_title')
    Sale
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Sales List') }}
                            </span>
                            @if(Auth::user())  
                             <div class="float-right">
                                <a href="{{ route('sales.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                            @endif
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    @if ($message = Session::get('error'))
                        <div class="alert alert-danger">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Client Name</th>
										<th>Discount</th>
										<th>Iva</th>
										<th>Total Amount</th>
										<th>Date Sale</th>
                                        @if(Auth::user())    
                                            <th>Actions</th>
                                        @endif
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($sales as $sale)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>
                                            @if(Auth::user()) 
                                                {{ $sale->client->name }}
                                            @endif
                                            </td>
											<td>$ @convert($sale->discount)</td>
											<td>$ @convert($sale->iva )</td>
											<td>$ @convert( $sale->total_amount)</td>
											<td> {{date('d-m-Y', strtotime($sale->date_sale));}}</td>
                                            @if(Auth::user())
                                            <td>
                                                <form action="{{ route('sales.destroy',$sale->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('sales.show',$sale->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('sales.edit',$sale->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                            @endif
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $sales->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/sale/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $sale->client->name ?? 'Show Sale' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">
                                <h5>Sale #  {{ $sale->id }}   </h5>
                                <div class="form-group">
                                    <strong>Client:</strong>
                                    {{ $sale->client->name }}    &nbsp;&nbsp;   <strong>Date:</strong>  {{date('d-m-Y', strtotime($sale->date_sale));}}
                                </div>

                            </span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('sales.index') }}"> Back</a>
                            <a class="btn btn-success" href="{{ route('sales.edit',$sale->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                        </div>
                    </div>

                    <div class="card-body">
                        

                        <span class="card-title">Sale Details</span>

                        <div class="table-responsive">
                            <table class="table table-striped table-hover" id="table_details">
                                <thead class="thead">
                                    <tr>
                                        <th>#</th>
                                        <th>Product</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Subtotal</th>
                                        <th>Iva</th>
                                    </tr>
                                </thead>
                                <tbody >
                                    @foreach ($sale->details as $detail)
                                        <tr>
                                            <td>{{ 1 }}</td>
                                            
											<td> {{ $detail->product->name }}</td>
											<td> $ @convert($detail->product->price)</td>
											<td> {{ $detail->quantity  }}</td>
                                            <td> $ @convert($detail->subtotal)</td>
                                            <td> $ @convert($detail->subtotal * 0.19)</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                                    <div class="col-md-3 resume">
                                        <div class="row number_resume">
                                            <div class="form-group">
                                                <strong>Total Amount:</strong>
                                                $ @convert($sale->total_amount)
                                            </div>
                                        </div>
                                        <div class="row number_resume">
                                                <div class="form-group">
                                                    <strong>Iva:</strong>
                                                $  @convert($sale->iva)
                                                </div>
                                        </div>
                                        <div class="row number_resume">
                                                <div class="form-group">
                                                    <strong>Discount:</strong>
                                                $  @convert($sale->discount) 
                                                </div>
                                        </div>
                                    </div>
                                
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection